Desktop version
VTY1999/Portfolio-setup-and-mobile-version-skeleton pull request #5
Opened 2021-12-08 15:25 UTC by VTY1999

**These are changes i have implemented for this project**

- Add media queries

- Create a new branch

- Create a linters for html and css

2021-12-08 18:15 UTC, HENRYKC24 requested changes
# STATUS: CHANGES REQUESTED :recycle:
## Hi @VTY1999 :wave:, 
![Close](https://media.giphy.com/media/WTdg5GBR45X6NbxqJK/giphy.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- [ ] Your commit message looks good but I think they need to be improved. A good commit message always starts with a **verb** and summarized what task you performed in that commit. It should describe the job done on that very commit (checkpoint).
**Your commit messages**
![image](https://user-images.githubusercontent.com/45668340/145259627-5cc6eacc-8c57-4493-84b3-e07e4e7e1803.png)
**Let's take a look at this**:point_down:
![image](https://user-images.githubusercontent.com/45668340/145260463-1e695a35-b674-4cf5-a82b-bc065f7be1b6.png)
[Read more here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)

- [ ] You can also improve your readme file a little bit. Instead of leaving a generic image in the readme file, why not use the image of the portfolio. That would be great, wouldn't it?
Please, change the image below to your portfolio image.
![image](https://user-images.githubusercontent.com/45668340/145261137-5c776f45-47fb-4ba2-919a-cadb8958b3ea.png)

- [ ] I think your file structure can also be improved. Since there is a folder called `images` it would be cleaner if you take all image files inside that folder. What do you think?:thinking:
![image](https://user-images.githubusercontent.com/45668340/145261619-742ff63f-64c6-4bf3-bae7-9084a10c70c0.png)



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-08 18:15 UTC, HENRYKC24 commented on index.html
>  <link rel="stylesheet" href="style.css">
[OPTIONAL] (**Highly recommended**)
I am of the opinion that HTML `link` element is placed in the `head` tag of the document. The HTML `body` element holds elements that define the structure of the webpage. Since the `link` element does not define the structure of the document, it is needless to have it inside the `body` tag. It would be ideal to have it in the `head`. What do you think?

2021-12-08 18:15 UTC, HENRYKC24 commented on index.html
>  <body>
- [ ] You actually made a frantic effort coding up your desktop version to look exactly as the design template. Well done:+1:. However, your mobile version UI is broken. **The app scrolls from left to right**. It is a good practice to maintain the design of both the mobile and desktop versions at all times. This is because there are so many users who will be viewing your app with a mobile device (recruiters inclusive) and at the same time, many will view it on a desktop. Please, consider making sure that both versions are intact. 
The mobile version scrolls from left to right, which is not very good for mobile users as they have to scroll from left to right trying to view the content of the webpage. Can you make it look exactly as it is in the template? I know you can do this:muscle:
## Your app as it is
![image](https://user-images.githubusercontent.com/45668340/145258407-c33ca8b8-6701-4ca0-a215-958c8a282693.png)

2021-12-09 11:36 UTC, elyor-doniyorov requested changes
Hi @VTY1999, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- [ ] Your Readme is still missing your portfolio screenshot.  Let's do the requested changes by the previous reviewer. 
- [ ] I can see you have added your all images in the images folder 👌. But also make sure to delete those duplicated images in your project directory because now you have them in the images folder.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-09 12:10 UTC, Rustamxon7 approved these changes
## Hi @VTY1999  👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![image](https://user-images.githubusercontent.com/69011963/145393994-80e9cfff-0ff4-4709-88a2-3aea44230559.png)


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-10 16:42 UTC, merged